# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'study_6.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(1000, 800)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Dialog.setFocusPolicy(QtCore.Qt.NoFocus)
        Dialog.setAccessibleDescription("")
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(False)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 239, 711, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.power_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.power_layout.setContentsMargins(0, 0, 0, 0)
        self.power_layout.setObjectName("power_layout")
        self.power_label_1 = QtWidgets.QLabel(Dialog)
        self.power_label_1.setGeometry(QtCore.QRect(10, 200, 711, 31))
        self.power_label_1.setAutoFillBackground(False)
        self.power_label_1.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 100), stop:1 rgba(255, 255, 255, 255));")
        self.power_label_1.setObjectName("power_label_1")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(720, 350, 16, 441))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(10, 340, 981, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 100, 711, 91))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.power_layout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.power_layout_2.setContentsMargins(0, 0, 0, 0)
        self.power_layout_2.setObjectName("power_layout_2")
        self.turbine_label_1 = QtWidgets.QLabel(Dialog)
        self.turbine_label_1.setGeometry(QtCore.QRect(10, 60, 711, 31))
        self.turbine_label_1.setAutoFillBackground(False)
        self.turbine_label_1.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 100), stop:1 rgba(255, 255, 255, 255));")
        self.turbine_label_1.setObjectName("turbine_label_1")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 360, 691, 441))
        self.label.setStyleSheet("image: url(../qt_resource/Study_6_re/System.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.turbine_label_2 = QtWidgets.QLabel(Dialog)
        self.turbine_label_2.setGeometry(QtCore.QRect(446, 360, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.turbine_label_2.setFont(font)
        self.turbine_label_2.setObjectName("turbine_label_2")
        self.power_label_2 = QtWidgets.QLabel(Dialog)
        self.power_label_2.setGeometry(QtCore.QRect(83, 617, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.power_label_2.setFont(font)
        self.power_label_2.setObjectName("power_label_2")
        self.arlarm_1 = QtWidgets.QPushButton(Dialog)
        self.arlarm_1.setGeometry(QtCore.QRect(740, 390, 74, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.arlarm_1.setFont(font)
        self.arlarm_1.setToolTip("")
        self.arlarm_1.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.arlarm_1.setObjectName("arlarm_1")
        self.arlarm_2 = QtWidgets.QPushButton(Dialog)
        self.arlarm_2.setGeometry(QtCore.QRect(740, 450, 74, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.arlarm_2.setFont(font)
        self.arlarm_2.setToolTip("")
        self.arlarm_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.arlarm_2.setObjectName("arlarm_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(740, 360, 251, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 360, 251, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 251, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.arlarm_3 = QtWidgets.QPushButton(Dialog)
        self.arlarm_3.setGeometry(QtCore.QRect(740, 510, 74, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.arlarm_3.setFont(font)
        self.arlarm_3.setToolTip("")
        self.arlarm_3.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.arlarm_3.setObjectName("arlarm_3")
        self.Logo = QtWidgets.QLabel(Dialog)
        self.Logo.setGeometry(QtCore.QRect(820, 10, 171, 71))
        self.Logo.setStyleSheet("image: url(../qt_resource/Study_6_re/Lab_log.png);")
        self.Logo.setText("")
        self.Logo.setObjectName("Logo")
        self.label.raise_()
        self.verticalLayoutWidget.raise_()
        self.power_label_1.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.turbine_label_1.raise_()
        self.turbine_label_2.raise_()
        self.power_label_2.raise_()
        self.arlarm_1.raise_()
        self.arlarm_2.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.arlarm_3.raise_()
        self.Logo.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.power_label_1.setText(_translate("Dialog", "Reactor power : "))
        self.turbine_label_1.setText(_translate("Dialog", "Turbine Load"))
        self.turbine_label_2.setText(_translate("Dialog", "Turbine Load"))
        self.power_label_2.setText(_translate("Dialog", "Power"))
        self.arlarm_1.setText(_translate("Dialog", "IR Block\n"
" State"))
        self.arlarm_2.setText(_translate("Dialog", "PR Block\n"
" State"))
        self.label_2.setText(_translate("Dialog", "Alarm Part"))
        self.label_3.setText(_translate("Dialog", "System Overview"))
        self.label_4.setText(_translate("Dialog", "Trand View"))
        self.arlarm_3.setText(_translate("Dialog", "Test blick"))

