# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'study_7.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(801, 559)
        self.cal = QtWidgets.QPushButton(Dialog)
        self.cal.setGeometry(QtCore.QRect(20, 210, 361, 23))
        self.cal.setObjectName("cal")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(20, 20, 361, 181))
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textEdit.setDocumentTitle("")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(199, 240, 181, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.val_2_1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.val_2_1.setObjectName("val_2_1")
        self.verticalLayout_2.addWidget(self.val_2_1)
        self.val_2_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.val_2_2.setObjectName("val_2_2")
        self.verticalLayout_2.addWidget(self.val_2_2)
        self.val_2_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.val_2_3.setObjectName("val_2_3")
        self.verticalLayout_2.addWidget(self.val_2_3)
        self.val_2_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.val_2_4.setObjectName("val_2_4")
        self.verticalLayout_2.addWidget(self.val_2_4)
        self.val_2_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.val_2_5.setObjectName("val_2_5")
        self.verticalLayout_2.addWidget(self.val_2_5)
        self.out_pro = QtWidgets.QTextEdit(Dialog)
        self.out_pro.setGeometry(QtCore.QRect(20, 450, 361, 91))
        self.out_pro.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.out_pro.setReadOnly(True)
        self.out_pro.setObjectName("out_pro")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(19, 240, 171, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.val_1_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.val_1_11.setObjectName("val_1_11")
        self.gridLayout.addWidget(self.val_1_11, 8, 0, 1, 1)
        self.val_1_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.val_1_16.setObjectName("val_1_16")
        self.gridLayout.addWidget(self.val_1_16, 10, 1, 1, 1)
        self.val_1_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.val_1_2.setObjectName("val_1_2")
        self.gridLayout.addWidget(self.val_1_2, 3, 1, 1, 1)
        self.val_1_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.val_1_12.setObjectName("val_1_12")
        self.gridLayout.addWidget(self.val_1_12, 8, 1, 1, 1)
        self.val_1_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.val_1_13.setObjectName("val_1_13")
        self.gridLayout.addWidget(self.val_1_13, 9, 0, 1, 1)
        self.val_1_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.val_1_14.setObjectName("val_1_14")
        self.gridLayout.addWidget(self.val_1_14, 9, 1, 1, 1)
        self.val_1_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.val_1_15.setObjectName("val_1_15")
        self.gridLayout.addWidget(self.val_1_15, 10, 0, 1, 1)
        self.val_1_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.val_1_8.setObjectName("val_1_8")
        self.gridLayout.addWidget(self.val_1_8, 6, 1, 1, 1)
        self.val_1_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.val_1_6.setObjectName("val_1_6")
        self.gridLayout.addWidget(self.val_1_6, 5, 1, 1, 1)
        self.val_1_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.val_1_1.setObjectName("val_1_1")
        self.gridLayout.addWidget(self.val_1_1, 3, 0, 1, 1)
        self.val_1_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.val_1_10.setObjectName("val_1_10")
        self.gridLayout.addWidget(self.val_1_10, 7, 1, 1, 1)
        self.val_1_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.val_1_7.setObjectName("val_1_7")
        self.gridLayout.addWidget(self.val_1_7, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 2)
        self.val_1_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.val_1_3.setObjectName("val_1_3")
        self.gridLayout.addWidget(self.val_1_3, 4, 0, 1, 1)
        self.val_1_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.val_1_5.setObjectName("val_1_5")
        self.gridLayout.addWidget(self.val_1_5, 5, 0, 1, 1)
        self.val_1_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.val_1_9.setObjectName("val_1_9")
        self.gridLayout.addWidget(self.val_1_9, 7, 0, 1, 1)
        self.val_1_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.val_1_4.setObjectName("val_1_4")
        self.gridLayout.addWidget(self.val_1_4, 4, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(390, 20, 391, 521))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.out_list = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.out_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.out_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.out_list.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.out_list.setReadOnly(True)
        self.out_list.setObjectName("out_list")
        self.gridLayout_2.addWidget(self.out_list, 3, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 2, 0, 1, 2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cal.setText(_translate("Dialog", "탐색"))
        self.label_2.setText(_translate("Dialog", "- 진단 관련 -"))
        self.val_2_1.setText(_translate("Dialog", "확인 :"))
        self.val_2_2.setText(_translate("Dialog", "점검 :"))
        self.val_2_3.setText(_translate("Dialog", "평가 :"))
        self.val_2_4.setText(_translate("Dialog", "감시 :"))
        self.val_2_5.setText(_translate("Dialog", "발생 : "))
        self.val_1_11.setText(_translate("Dialog", "시도 :"))
        self.val_1_16.setText(_translate("Dialog", "시작 :"))
        self.val_1_2.setText(_translate("Dialog", "조치 : "))
        self.val_1_12.setText(_translate("Dialog", "사용 :"))
        self.val_1_13.setText(_translate("Dialog", "정지 :"))
        self.val_1_14.setText(_translate("Dialog", "실시 : "))
        self.val_1_15.setText(_translate("Dialog", "유지 :"))
        self.val_1_8.setText(_translate("Dialog", "차단 : "))
        self.val_1_6.setText(_translate("Dialog", "복구 :"))
        self.val_1_1.setText(_translate("Dialog", "조절 : "))
        self.val_1_10.setText(_translate("Dialog", "기동 : "))
        self.val_1_7.setText(_translate("Dialog", "충수 :"))
        self.label_4.setText(_translate("Dialog", "- 제어 관련 - "))
        self.val_1_3.setText(_translate("Dialog", "수행 :"))
        self.val_1_5.setText(_translate("Dialog", "재설정 :"))
        self.val_1_9.setText(_translate("Dialog", "배기 :"))
        self.val_1_4.setText(_translate("Dialog", "전환 : "))
        self.label.setText(_translate("Dialog", "절차서 탐색기"))

